<?php
$_data = array(
	'Cart' => __('Carrello'),
	'Go to Cart' => __('Go to Cart'),
	'Sorry, no quotes are available for this order at this time' => __('Sorry, no quotes are available for this order at this time'),
	'Item in Cart' => __('Item in Cart'),
	'Already have an account?' => __('Already have an account?'),
	'Recently added item(s)' => __('Recently added item(s)'),
	'Checkout now to earn' => __('Checkout now to earn'),
	'Spend Your Points' => __('Spend Your Points'),
	'You have %s' => __('You have %s'),
	'Choose how many points to spend' => __('Choose how many points to spend'),
	'You will spend' => __('You will spend'),
	'Please specify a shipping method.' => __('Please specify a shipping method.'),
	'Already have an account? Click here to login' => __('Already have an account? Click here to login'),
	'Register for newsletter' => __('Register for newsletter'),
	'Create account' => __('Create account'),
	'You will be redirected for payment processing.' => __('You will be redirected for payment processing.'),
	'New Address' => __('New Address'),
	'You already have an account with us.' => __('You already have an account with us.'),
	'or continue as guest.' => __('or continue as guest.'),
	'You\'ll be redirected to Stripe to complete your payment using one of the following payment methods:' => __('You\'ll be redirected to Stripe to complete your payment using one of the following payment methods:')
);
?>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W6VMB4R');</script>
<!-- End Google Tag Manager -->
<script>
    require(
		[
			'jquery',
			'mage/translate'
		],
		function ($) {
			$.mage.translate.add(<?php echo Zend_Json::encode($_data) ?>);

			$('#mobile-nav li.level0.nav-6.category-item .submenu > a, #mobile-nav li.level0.nav-5.category-item .submenu > a').on('click touchstart', function() {
				window.location.href = $(this).attr('href');
				$(this).css('pointer-events', 'none');
			});
		}
	);
</script>
<!-- <script>
    require(
		[
			'jquery'
		],
		function ($) {
			//0 - desktop, 1 - mobile
			var mode = 0;

			var getScreenMode = function() {
				var curWidth = $(window).width();
				if (curWidth < 768) return 1;
				return 0;
			};

			var toDoTrustpilot = function(newMode) {
				var target = $('#trustpilot-widget-trustbox-0-wrapper');
				if (target.length == 0) return;
				if (newMode == 1) {
					$('.menu-wrapper .block.block-content > .form.minisearch').before(target);
					return;
				}
				if (newMode == 0) {
					$('.header-wrapper > .page-header > .middle-block').prepend(target);
					return;
				}
			};

			var toDoOnResize = function() {
				var curMode = getScreenMode();
				if (curMode == mode) return;
				toDoTrustpilot(curMode);
				mode = curMode;
			};

			$(window).resize(function() {
				toDoOnResize();
			});

			toDoOnResize();
		}
	);
</script> -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link  rel="stylesheet" type="text/css"  media="all" href="/pub/css/custom.css?v=1.32" />
<style type="text/css">
	/*#checkoutSteps .checkout-payment-method .checkout-billing-address + .discount-code {
		display: none !important;
	}*/
	@media (max-width: 1199px) {
		.back-link {
			margin-bottom: 8px !important;
		}
	}
</style>
