<?php
$_data = array(
	'Cart' => __('Carrello'),
	'Go to Cart' => __('Go to Cart'),
	'Sorry, no quotes are available for this order at this time' => __('Sorry, no quotes are available for this order at this time'),
	'Item in Cart' => __('Item in Cart'),
	'Already have an account?' => __('Already have an account?'),
	'Recently added item(s)' => __('Recently added item(s)'),
	'Checkout now to earn' => __('Checkout now to earn'),
	'Spend Your Points' => __('Spend Your Points'),
	'You have %s' => __('You have %s'),
	'Choose how many points to spend' => __('Choose how many points to spend'),
	'You will spend' => __('You will spend'),
	'Please specify a shipping method.' => __('Please specify a shipping method.')
);
?>
<script>
    require(
		[
			'jquery',
			'mage/translate'
		],
		function ($) {
			$.mage.translate.add(<?php echo Zend_Json::encode($_data) ?>);
		}
	);
</script>
<!-- <script>
    require(
		[
			'jquery'
		],
		function ($) {
			//0 - desktop, 1 - mobile
			var mode = 0;

			var getScreenMode = function() {
				var curWidth = $(window).width();
				if (curWidth < 768) return 1;
				return 0;
			};

			var toDoTrustpilot = function(newMode) {
				var target = $('#trustpilot-widget-trustbox-0-wrapper');
				if (target.length == 0) return;
				if (newMode == 1) {
					$('.menu-wrapper .block.block-content > .form.minisearch').before(target);
					return;
				}
				if (newMode == 0) {
					$('.header-wrapper > .page-header > .middle-block').prepend(target);
					return;
				}
			};

			var toDoOnResize = function() {
				var curMode = getScreenMode();
				if (curMode == mode) return;
				toDoTrustpilot(curMode);
				mode = curMode;
			};

			$(window).resize(function() {
				toDoOnResize();
			});

			toDoOnResize();
		}
	);
</script> -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link  rel="stylesheet" type="text/css"  media="all" href="/pub/css/custom.css?v=1.24" />
<style type="text/css">
	#checkoutSteps .checkout-payment-method .checkout-billing-address + .discount-code {
		display: none !important;
	}
</style>