<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<?php $_isRequestProduct = $this->helper('Datacom\CuraNatura\Helper\Data')->getRequestParam('request_product') == '1'; ?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span>
			<?php if ($_isRequestProduct): ?>
				<?= $block->escapeHtml(__('Request a product')) ?>
			<?php else: ?>
				<?= $block->escapeHtml(__('Write Us')) ?>
			<?php endif; ?>
		</span></legend><br />
        <div class="field note no-label"><?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
		<?php if ($_isRequestProduct): ?>
			<div class="field product-request required">
				<label class="label" for="product-request"><span><?= $block->escapeHtml(__('Request product')) ?></span></label>
				<div class="control">
					<input name="product-request" id="product-request" title="<?= $block->escapeHtmlAttr(__('Request product')) ?>" value="" class="input-text" type="text" />
				</div>
			</div>
		<?php endif; ?>
        <div class="field comment<?php if (!$_isRequestProduct) echo ' required'; ?>">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('Message content')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Message content')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<?php if ($_isRequestProduct): ?>
	<script type="text/javascript">
		require(
			[
				'jquery'
			],
			function ($) {
				$('#contact-form').on('submit', function() {
					var oldComment = $('#comment').val();
					$('#comment').val('Richiesta prodotto: ' + $('#product-request').val() + '\n-------\n' + oldComment);
				});
			}
		);

	</script>
<?php endif; ?>