<p class="doofinder-reccomends">Prodotti Raccomandati</p>
<script>
  var dfUrl = 'https://cdn.doofinder.com/recommendations/js/doofinderRecommendation.min.js';
  (function(c,o,k,e){var r,t,i=setInterval(function(){t+=c;r=typeof(require)==='function';
  if(t>=o||r)clearInterval(i);if(r)require([k],e)},c)})(100, 10000, dfUrl);
</script>
<df-recommendations
  hashid="bf62570e56323882b33e6519e11d6d5a"
  total-products="10">
</df-recommendations>
<style type="text/css">
  .product.custom.info {
    clear: both;
    padding-top: 50px;
    margin-bottom: 30px;
  }
  .doofinder-reccomends {
    font-family: barlow;
    color: rgba(0,0,0,.8);
    letter-spacing: -.2px;
    line-height: 1.1;
    font-size: 2.5rem;
    margin-bottom: 2rem;
    font-weight: bold;
    text-align: center;
  }
</style>