<!-- <script type="text/javascript" src="https://js.stripe.com/v3/"></script> -->
<script type="text/javascript">
    require(
        [
            'jquery'
        ],
        function($) {
            var checkFreeShipping = function() {
                var target = $('#checkout-shipping-method-load');

                if (target.length == 0) {
                    setTimeout(function() {
                        checkFreeShipping();
                    }, 50);
                    return;
                }

                var working = false;

                target.on('DOMSubtreeModified', function(){
                    if (working) return;

                    var shippingCountrySelected = $('#co-shipping-form .select[name="country_id"]');

                    if (shippingCountrySelected.length == 0) return;

                    var selectedCountry = shippingCountrySelected.val();

                    if (selectedCountry != 'IT') return;
                    
                    var subtotalWrapper = $('#minicart-content-wrapper .subtotal .price-wrapper .price');
                    if (subtotalWrapper.length == 0) return;
                    var subtotalHtml = subtotalWrapper.html().split("&")[0];
                    subtotalHtml = subtotalHtml.replace('.', '');
                    subtotalHtml = subtotalHtml.replace(',', '.');
                    var subtotal = parseFloat(subtotalHtml);

                    if (subtotal < 50) return;

                    var applyText = function() {
                        var rows = $('#checkout-shipping-method-load tbody tr');

                        if (rows.length == 0) {
                            setTimeout(function() {
                                applyText();
                            }, 50)
                            return;
                        }

                        if (rows.length != 2) return;

                        working = true;

                        $(rows[0]).find('.price > .price').html("2,00&nbsp;€");

                        var target = $(rows[1]).find('.price > .price');
                        target.html('<?= __('Free') ?>');
                        target.attr('dtm-free-shipping', '1');

                        working = false;
                    };
                    
                    applyText();
                });
            };

            checkFreeShipping();
        }
    );
</script>