<?php

$popupCookie = $this->helper('\Meigee\Coccinelle\Helper\FrontHelper')->getCookie('coccinellePopup');
$popupCookie2 = $this->helper('\Meigee\Coccinelle\Helper\FrontHelper')->getCookie('coccinellePopupFlag2');
if(!$popupCookie && !$popupCookie2):
	$meigee_helper = $this->helper('\Meigee\Coccinelle\Helper\CoccinelleGeneral');
	$popupStatus   = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'status');
	$expires       = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'expires');
	$popupWidth    = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'width');
	$popupHeight   = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'height');
	$popupStatic   = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'static');
	$popupOnlyHome = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'onlyhome');
	$popupMobile   = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'mobile');
	$popupTablet   = $meigee_helper->getCustomThemeOptionCnf('coccinelle_popup_content', 'tablet');
	$isHome        = $this->helper('\Meigee\Coccinelle\Helper\FrontHelper')->getCurrentPage() == 'cms_index_index';
	if(($popupOnlyHome && $isHome) || !$popupOnlyHome) {

?>

<div class="modal fade popup-block<?php echo(!$popupMobile ? ' mobile-hide' : '').''.(!$popupTablet ? ' tablet-hide' : ''); ?>" id="popup-block" tabindex="-1" role="dialog" aria-hidden="true" data-expires="<?php echo $expires; ?>">
  <div class="modal-dialog" style="width:<?php echo $popupWidth; ?>px;">
	<div class="modal-content" style="height: <?php echo $popupHeight; ?>px; width: <?php echo $popupWidth; ?>px; margin-top: -<?php echo ($popupHeight/2); ?>px;">
	  <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="meigee-close"></i></span></button>
	  </div>
	  <div class="modal-body clearfix">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($popupStatic)->toHtml(); ?>
		<label class="popup-bottom"><input type="checkbox"><?php echo __('Don&#39;t show again'); ?></label>
	  </div>
	</div>
  </div>
</div>
<script>
    require(
        [
            'jquery',
			'Meigee_Coccinelle/js/jquery.cookie',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
			cookie,
            modal
        ) {
			
			var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass: 'popup-block-modal',
                buttons: false,
				closed: function(){
				   $.cookie('coccinellePopup', 'true');
				}
            };
            var modalTmpl = modal(options, $('#popup-block'));
			
			console.log('4'); 
			
			function popupBlock() {
                $('#popup-block').modal('openModal');
            }
            subscribeFlag = $.cookie('coccinellePopup');


            $('#popup-block .action.subscribe').on('click', function(){
                if($('#popup-block').find('.mage-error').length == 0 && !$('#subscribecheck').attr('aria-invalid')) {
                    $.cookie('coccinellePopupFlag2', 'true', {
                        expires: 30,
                        path: '/'
                    });
                } else {
                    $.removeCookie('coccinellePopupFlag2');
                }
            });

            expires = $('#popup-block').data('expires');
            function subsSetcookie(){
                $.cookie('coccinellePopup', 'true', {
                    expires: expires,
                    path: '/'
                });
            }
			
			
			// $( document ).ready(function() {
			
				if(!(subscribeFlag) && !$.cookie('coccinellePopupFlag2')){
					console.log('3');
					popupBlock();
				}else{
					$.removeCookie('coccinellePopup', { path: '/' });
					subsSetcookie();
				}
			
			// });
			
            $('#popup-block').parents('body').css({
                'padding' : 0,
                'overflow' : 'visible'
            });
            $('#popup-block .popup-bottom input').on('click', function(){
                if($(this).parent().find('input:checked').length){
                    subsSetcookie();
                } else {
                    $.removeCookie('coccinellePopup', { path: '/' });
                }
            });

            if($('#popup-block .popup-content-wrapper').data('bgimg')){
                var bgImg = $('#popup-block .popup-content-wrapper').data('bgimg');
                $('#popup-block .popup-content-wrapper').attr('style', bgImg);
            }

            if ($('#popup-block .popup-bottom input:checked').length == 0) {
                $('#popup-block .popup-bottom input').click();
            }

            // $('a[data-toggle="modal"]').on('click', function() {
				// target = $(this).data('target');
				// content = $(document).find(target).children().clone();
				// $('#popup-modal').html(content);
				
			// });
        }
    );
</script>
<?php
	}
endif; ?>
